### ISSUE TITLE
ComputeHelper.rd and ComputeHelper.view null

### ISSUE THREAD

**Issue by emberlightstudios** [DevPoodle/compute-shader-plus#1]
I'm getting these static vars as null somehow.  I am trying to do some calcs in editor.  Not sure if that's related.  Maybe a simple @tool annotator would fix it.

**Comment by DevPoodle** [comment]
Thanks for opening the first issue! Just tested this myself and adding @tool seems to fix it just fine. Weirdly enough, static funcs and const vars both work completely okay without @tool, so it seems like the only script that needs the annotation is ComputeHelper. I'll merge a PR for this in a few minutes.
