### ISSUE TITLE
Texture requires the `RenderingDevice.TEXTURE_USAGE_CAN_COPY_FROM_BIT` to be set to be retrieved.

### ISSUE THREAD

**Issue by dragonryan06** [DevPoodle/compute-shader-plus#4]
So, obviously I don't know how RenderingDevice or this codebase works, but I am attempting to run the quickstart you provided in the readme with a simple glsl file that recolors every pixel magenta, and I'm getting this error on the line that is supposed to read the output of the shader. Is this something I did wrong on the shader end or is this a breaking change from Godot v4.3?

![image](https://github.com/user-attachments/assets/66a58879-4255-49a1-a195-bde6cca4736f)

It seems like the RenderingDevice wants to know in advance if a texture is going to be read, and that is not being set or something? That's what makes me think this is a Godot v4.3 issue.

Any help would be appreciated, this addon seems awesome!

**Comment by DevPoodle** [comment]
Hi! Thanks for opening an issue. I looked into it, and I had made a pretty simple mistake in one of the image format scripts. It should work fine now. Let me know if you're still running into any problems, or just need help using the plugin in general, thanks!
